schema_version = "1.0.0"

id = "Modifier_List_Fork"
version = "1.9.86"
name = "Modifier List"
tagline = "Enhanced Modifier UI/Features, now with Edit Mesh Modifier"
maintainer = "Antti Tikka, Draise, Dan-Gry"
type = "add-on"

website = "https://blenderartists.org/t/modifier-list-for-blender-4-2-addon-fork/1512291"

tags = ["Modeling", "User Interface"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Save Add-on Prefrences"
